"""
Problem 2


Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

"""

total = 0
previous_item = 0
current_item = 1


while current_item <= 4000000:
    
    if current_item % 2 == 0:
        total += current_item

    temp = current_item
    current_item += previous_item
    previous_item = temp

print('The sum of all even elements:' + str(total))
